import { showFestive } from './constant';
import defaultAvatar from '../assets/avatar/default.png';
import Avatar1 from '../assets/avatar/001.png';
import Avatar2 from '../assets/avatar/002.png';
import Avatar3 from '../assets/avatar/003.png';
import Avatar4 from '../assets/avatar/004.png';
import Avatar5 from '../assets/avatar/005.png';
import Avatar6 from '../assets/avatar/006.png';
import Avatar7 from '../assets/avatar/007.png';
import Avatar8 from '../assets/avatar/008.png';
import Avatar9 from '../assets/avatar/009.png';
import Avatar10 from '../assets/avatar/010.png';
import Avatar11 from '../assets/avatar/011.png';
import Avatar12 from '../assets/avatar/012.png';
import Avatar13 from '../assets/avatar/013.png';
import Avatar14 from '../assets/avatar/014.png';
import Avatar15 from '../assets/avatar/015.png';
import Avatar16 from '../assets/avatar/016.png';
import Avatar17 from '../assets/avatar/017.png';
import Avatar18 from '../assets/avatar/018.png';
import Avatar19 from '../assets/avatar/019.png';
import Avatar20 from '../assets/avatar/020.png';
import Avatar21 from '../assets/avatar/021.png';
import Avatar22 from '../assets/avatar/022.png';
import { DefaultFestiveProfile } from 'assets/festive/profile';

const getDefaultAvatar = () => {
	if (showFestive) {
		return DefaultFestiveProfile;
	}
	return defaultAvatar;
};

export const AVATAR_PACK = [
	{
		id: 0,
		image: getDefaultAvatar(),
	},
	{
		id: 1,
		image: Avatar1,
	},
	{
		id: 2,
		image: Avatar2,
	},
	{
		id: 3,
		image: Avatar3,
	},
	{
		id: 4,
		image: Avatar4,
	},
	{
		id: 5,
		image: Avatar5,
	},
	{
		id: 6,
		image: Avatar6,
	},
	{
		id: 7,
		image: Avatar7,
	},
	{
		id: 8,
		image: Avatar8,
	},
	{
		id: 9,
		image: Avatar9,
	},
	{
		id: 10,
		image: Avatar10,
	},
	{
		id: 11,
		image: Avatar11,
	},
	{
		id: 12,
		image: Avatar12,
	},
	{
		id: 13,
		image: Avatar13,
	},
	{
		id: 14,
		image: Avatar14,
	},
	{
		id: 15,
		image: Avatar15,
	},
	{
		id: 16,
		image: Avatar16,
	},
	{
		id: 17,
		image: Avatar17,
	},
	{
		id: 18,
		image: Avatar18,
	},
	{
		id: 19,
		image: Avatar19,
	},
	{
		id: 20,
		image: Avatar20,
	},
	{
		id: 21,
		image: Avatar21,
	},
	{
		id: 22,
		image: Avatar22,
	},
];

export const NOTIFICATION_COMPANY_LIST = [
	{ id: 1, name: 'Public Bank Berhad', code: 'PBB' },
	{ id: 2, name: 'Public Investment Bank Bhd', code: 'PIV' },
];

export const NOTIFICATION_CATEGORY_LIST = [
	{
		id: 2,
		name: 'Announcement',
		image: 'https://img.icons8.com/clouds/2x/commercial.png',
	},
	{
		id: 3,
		name: 'System',
		image: 'https://img.icons8.com/clouds/2x/support.png',
	},
	{ id: 4, name: 'Leave', image: 'https://img.icons8.com/clouds/2x/today.png' },
	{
		id: 5,
		name: 'Clinic',
		image: 'https://img.icons8.com/clouds/2x/hospital.png',
	},
	{
		id: 6,
		name: 'Meeting',
		image: 'https://img.icons8.com/clouds/2x/meeting-room.png',
	},
	{
		id: 7,
		name: 'Event',
		image: 'https://img.icons8.com/clouds/2x/important-event.png',
	},
	{
		id: 8,
		name: 'Promotion',
		image: 'https://img.icons8.com/clouds/2x/gif.png',
	},
];

export const LEAVE_CATEGORY = [
	{ code: 'PPH1', color: '#A8A8A8' },
	{ code: 'A001', color: '#C0E5FF' },
	{ code: 'M002', color: '#FFC3BF' },
	{ code: 'M003', color: '#C0CCFF' },
	{ code: 'M011', color: '#D7BFFF' },
	{ code: 'E001', color: '#FFC0E6' },
	{ code: 'C012', color: '#FFE1C0' },
	{ code: 'C006', color: '#FFE1C0' },
	{ code: 'R002', color: '#C0FFE7' },
	{ code: 'R003', color: '#E6FFC0' },
	{ code: 'M010', color: '#FFD9C0' },
	{ code: 'M014', color: '#FFD9C0' },
	{ code: 'N002', color: '#C0E5FF' },
	{ code: 'P004', color: '#BFFFFF' },
	{ code: 'T001', color: '#FFC3BF' },
];

export const LEAVE_COLOR_CODES = {
	PPH1: '#A8A8A8',
	A001: '#C0E5FF',
	M002: '#FFC3BF',
	M003: '#C0CCFF',
	M011: '#D7BFFF',
	E001: '#FFC0E6',
	C012: '#FFE1C0',
	C006: '#FFE1C0',
	R002: '#C0FFE7',
	R003: '#E6FFC0',
	M010: '#FFD9C0',
	M014: '#FFD9C0',
	N002: '#C0E5FF',
	P004: '#BFFFFF',
	T001: '#FFC3BF',
};

export const NEWS_LIST = [];
export const TRAINING_LIST = [];
export const MEETING_LIST = [];
export const EVENT_LIST = [];

export const PROMOTIONS_LIST = [];

export const PANEL_LIST = [
	{
		code: 'SH25',
		lat: 0,
		long: 0,
		clinicCode: null,
		name: '24 JAM KLINIK & SURGERI DONGGONGON',
		panelType: null,
		tel: '088-726866',
		hour: '24 HOURS',
		addr: "GRD FLR, LOT 1 BLK F, SEDCO D'NGONGON SHOPHOUSES,",
		zip: '89500',
		area: 'PENAMPANG',
		state: 'SABAH',
		personId: null,
		companyCode: null,
		noOfDays: 0,
		staffNo: null,
		divisionCode: null,
		divisionGrpCode: null,
		requesterStaffNo: null,
		maxGradeCode: null,
		status: null,
		stYmth: null,
		edYmth: null,
		startDate: null,
	},
	{
		code: 'PK68',
		lat: 0,
		long: 0,
		clinicCode: null,
		name: 'ARUN KELINIK (MAIN CLINIC)',
		panelType: null,
		tel: '005-5981350',
		hour: 'DAILY 8:30AM-5PM',
		addr: '135 JLN BESAR, SG SIPUT (U),',
		zip: '31100',
		area: 'SG SIPUT',
		state: 'PERAK',
		personId: null,
		companyCode: null,
		noOfDays: 0,
		staffNo: null,
		divisionCode: null,
		divisionGrpCode: null,
		requesterStaffNo: null,
		maxGradeCode: null,
		status: null,
		stYmth: null,
		edYmth: null,
		startDate: null,
	},
	{
		code: 'PP36',
		lat: 0,
		long: 0,
		clinicCode: null,
		name: 'ASIA KLINIK',
		panelType: null,
		tel: '004-6595536',
		hour: 'M-F 9AM-9:30PM; ↵SAT/SUN/PH 9AM-12:30PM',
		addr: '19-D TMN SRI DAMAI, LEBUHRAYA BT LANCANG, PENANG',
		zip: '11600',
		area: 'P.PINANG',
		state: 'PULAU PINANG',
		personId: null,
		companyCode: null,
		noOfDays: 0,
		staffNo: null,
		divisionCode: null,
		divisionGrpCode: null,
		requesterStaffNo: null,
		maxGradeCode: null,
		status: null,
		stYmth: null,
		edYmth: null,
		startDate: null,
	},
	{
		code: 'HSL4',
		lat: 0,
		long: 0,
		clinicCode: null,
		name: 'ASSUNTA HOSPITAL',
		panelType: null,
		tel: '003-76807000',
		hour: '',
		addr: 'JALAN TEMPLER',
		zip: '46990',
		area: 'PJ',
		state: 'SELANGOR',
		personId: null,
		companyCode: null,
		noOfDays: 0,
		staffNo: null,
		divisionCode: null,
		divisionGrpCode: null,
		requesterStaffNo: null,
		maxGradeCode: null,
		status: null,
		stYmth: null,
		edYmth: null,
		startDate: null,
	},
	{
		code: 'SK59',
		lat: 0,
		long: 0,
		clinicCode: null,
		name: "B. KONG'S CLINIC",
		panelType: null,
		tel: '084-346388',
		hour: 'M/W/F 8AM-9PM; ↵TUE/THU/SAT 8AM-5PM;  ↵SUN/PH 8AM-12PM',
		addr: '6-D BROOKE DRIVE,',
		zip: '96000',
		area: 'SIBU',
		state: 'SARAWAK',
		personId: null,
		companyCode: null,
		noOfDays: 0,
		staffNo: null,
		divisionCode: null,
		divisionGrpCode: null,
		requesterStaffNo: null,
		maxGradeCode: null,
		status: null,
		stYmth: null,
		edYmth: null,
		startDate: null,
	},
	{
		code: 'HPP2',
		lat: 0,
		long: 0,
		clinicCode: null,
		name: 'BAGAN SPECIALIST CENTRE',
		panelType: null,
		tel: '004-3322800',
		hour: '',
		addr: 'JALAN BAGAN 1,',
		zip: '13400',
		area: 'BUTTERWORTH',
		state: 'PULAU PINANG',
		personId: null,
		companyCode: null,
		noOfDays: 0,
		staffNo: null,
		divisionCode: null,
		divisionGrpCode: null,
		requesterStaffNo: null,
		maxGradeCode: null,
		status: null,
		stYmth: null,
		edYmth: null,
		startDate: null,
	},
	{
		code: 'PK31',
		lat: 0,
		long: 0,
		clinicCode: null,
		name: 'BERCHAM MEDICAL CENTRE',
		panelType: null,
		tel: '005-5361901',
		hour: '24 HOURS',
		addr: '10 PERSIARAN MEDAN BERCHAM 6, PUSAT BANDARBARU BERCHAM',
		zip: '31400',
		area: 'JLN BERCHAM',
		state: 'PERAK',
		personId: null,
		companyCode: null,
		noOfDays: 0,
		staffNo: null,
		divisionCode: null,
		divisionGrpCode: null,
		requesterStaffNo: null,
		maxGradeCode: null,
		status: null,
		stYmth: null,
		edYmth: null,
		startDate: null,
	},
	{
		code: 'SL13',
		lat: 0,
		long: 0,
		clinicCode: null,
		name: 'BINA KELINIK',
		panelType: null,
		tel: '003-31871029',
		hour: 'M-F 9AM-6PM; ↵WED/SAT 9AM-5PM',
		addr: '186 JALAN SULTAN ABDUL SAMAD,',
		zip: '42700',
		area: 'BANTING',
		state: 'SELANGOR',
		personId: null,
		companyCode: null,
		noOfDays: 0,
		staffNo: null,
		divisionCode: null,
		divisionGrpCode: null,
		requesterStaffNo: null,
		maxGradeCode: null,
		status: null,
		stYmth: null,
		edYmth: null,
		startDate: null,
	},
];
export const PANEL_STATE_LIST = [
	{
		state: 'ALL STATES',
		area: ['ALL STATES'],
	},
	{
		state: 'BATTAMBANG',
		area: ['SANGKAT SVAY POR'],
	},
	{
		state: 'BAVET',
		area: ['SVAY REANG PROVINCE'],
	},
	{
		state: 'JOHOR',
		area: [
			'BATU PAHAT',
			'BUKIT PASIR',
			'CHAAH',
			'ENDAU',
			'J.BAHRU',
			'JOHOR BAHRU',
			'KLUANG',
			'KOTA TINGGI',
			'KULAI',
			'MASAI',
			'MERSING',
			'MUAR',
			'PAGOH',
			'PALOH',
			'PASIR GUDANG',
			'PEKAN NENAS',
			'PLENTONG',
			'PONTIAN KECIL',
			'SEGAMAT',
			'SENAI',
			'SIMPANG RENGAM',
			'SKUDAI',
			'SRI TEBRAU',
			'TAMPOI',
			'TANGKAK',
			'TMN CENTURY',
			'TMN DESA CEMERLANG',
			'TMN JOHOR JAYA',
			'TMN PERLING',
			'TMN SENTOSA',
			'TMN SERI BAHAGIA',
			'TMN SRI BAHAGIA',
			'ULU TIRAM',
			'YONG PENG',
		],
	},
	{
		state: 'KAMPONG CHAM',
		area: ['KRONG KAMPONG CHAM'],
	},
	{
		state: 'KAMPOT',
		area: ['KAMPOT PROVINCE'],
	},
	{
		state: 'KEDAH',
		area: [
			'ALOR SETAR',
			'BALING',
			'CHANGLUN',
			'GUAR CEMPEDAK',
			'GURUN',
			'JITRA',
			'K.KETIL',
			'KULIM',
			'LUNAS',
			'P.LANGKAWI',
			'POKOK SENA',
			'SG PETANI',
			'SIK',
		],
	},
	{
		state: 'KELANTAN',
		area: [
			'GUA MUSANG',
			'K.KRAI',
			'KOTA BAHRU',
			'KUALA KRAI',
			'MACHANG',
			'PASIR MAS',
			'PASIR PUTEH',
			'TANAH MERAH',
		],
	},
	{
		state: 'KUALA LUMPUR',
		area: [
			'AMPANG',
			'BANDAR SRI DAMANSARA',
			'BANGSAR',
			'BATU CAVES',
			'BRICKFIELDS',
			'BUKIT DAMANSARA',
			'CAPITAL SQUARE',
			'CHERAS',
			'DAMANSARA',
			'DAMANSARA HEIGHTS',
			'DESA PANDAN',
			'GOMBAK',
			'JINJANG',
			'JLN ALOR',
			'JLN BUKIT BINTANG',
			'JLN BUKIT NENAS',
			'JLN CHEMUR  ',
			'JLN HANG LEKIU',
			'JLN HJ HUSSIEN',
			'JLN IPOH',
			'JLN KELANG LAMA',
			'JLN KENANGA',
			'JLN KUCHAI LAMA',
			'JLN LOKE YEW',
			'JLN MASJID INDIA',
			'JLN P RAMLEE',
			'JLN PAHANG',
			'JLN PUTRA',
			'JLN RAJA CHULAN',
			'JLN RAJA LAUT',
			'JLN RAJA MUDA ABD AZIZ',
			'JLN SEMANTAN',
			'JLN SG BESI',
			'JLN SULTAN ISMAIL',
			'JLN SULTAN SULAIMAN',
			'JLN TUN RAZAK',
			'JLN TUN TAN SIEW',
			'JLN TUNKU ABD RAHMAN',
			'KAMPUNG BARU',
			'KEPONG',
			'KL CENTRAL',
			'MEDAN PASAR',
			'OUG',
			'PANDAN INDAH',
			'PANDAN JAYA',
			'PANDAN PERDANA',
			'PUDU',
			'PUTRAJAYA',
			'SALAK SOUTH',
			'SEGAMBUT',
			'SENTUL',
			'SERI PETALING',
			'SETAPAK',
			'SRI HARTAMAS',
			'TAMAN DESA',
			'TAMAN MUDA',
			'TMN ANGSANA HILIR',
			'TMN DESA',
			'TMN DESA PETALING',
			'TMN DESA SETAPAK',
			'TMN KERAMAT',
			'TMN MELAWATI',
			'TMN SETIAWANGSA',
			'ULU KELANG',
			'WANGSA MAJU',
		],
	},

	{
		state: 'MELAKA',
		area: [
			'AIR KEROH',
			'AMPANG',
			'BACHANG',
			'BKT BARU',
			'BUKIT BERENDAM',
			'JASIN',
			'JLN BENDAHARA',
			'JLN MELAKA',
			'MASJID TANAH',
			'MELAKA',
			'TMN MALIM JAYA',
			'TREE',
		],
	},
	{
		state: 'NEGERI SEMBILAN',
		area: [
			'BAHAU',
			'BATANG MELAKA',
			'GEMAS',
			'GEMENCHEH',
			'JELEBU',
			'K.KELAWANG',
			'KUALA PILAH',
			'NILAI',
			'PORT DICKSON',
			'RANTAU',
			'RASAH',
			'SEREMBAN',
			'TAMAN SENTOSA DAMAI',
			'TAMPIN',
		],
	},
	{
		state: 'PAHANG',
		area: [
			'BENTONG',
			'BRINCHANG',
			'GENTING HIGHLANDS',
			'JERANTUT',
			'KARAK',
			'KEMAYAN',
			'KUALA .LIPIS',
			'KUALA KRAU',
			'KUALA LIPIS',
			'KUANTAN',
			'MENTAKAB',
			'PEKAN',
			'RAUB',
			'TANAH RATA',
			'TEMERLOH',
			'TRIANG',
		],
	},
	{
		state: 'PERAK',
		area: [
			'AIR TAWAR',
			'BAGAN SERAI',
			'BATU GAJAH',
			'BIDOR',
			'CHEMOR',
			'GUNUNG RAPAT',
			'IPOH',
			'IPOH GARDEN',
			'JLN BERCHAM',
			'JLN PASIR PUTIH',
			'JLN YANG KALSOM',
			'KAMPAR',
			'KAMUNTING',
			'KUALA KANGSAR',
			'LUMUT',
			'MENGLEMBU',
			'PANGKOR',
			'PANTAI REMIS',
			'PARIT BUNTAR',
			'PENGKALAN BARAT',
			'PUSING',
			'SERI MANJUNG',
			'SG SIPUT',
			'SIMPANG AMPAT',
			'SIMPANG PULAI',
			'SITIAWAN',
			'SLIM RIVER',
			'TAIPING',
			'TANJUNG MALIM',
			'TANJUNG PIANDANG',
			'TELUK INTAN',
		],
	},
	{
		state: 'PERLIS',
		area: ['K.PERLIS', 'KANGAR'],
	},
	{
		state: 'PHNOM PENH',
		area: ['PHNOM PENH'],
	},
	{
		state: 'POI PET',
		area: ['POI PET CITY, BANTEYMEANCHEY PROVINCE'],
	},
	{
		state: 'PULAU PINANG',
		area: [
			'AIR ITAM',
			'BAGAN AJAM',
			'BALIK PULAU',
			'BANDAR BARU AIR ITAM',
			'BAYAN BARU',
			'BUKIT MERTAJAM',
			'BUTTERWORTH',
			'GELUGOR',
			'JELUTONG',
			'JLN DATUK KERAMAT',
			'JLN PANGKOR',
			'JLN TAN SRI TEH EWE LIM',
			'KEPALA BATAS',
			'LOGAN ROAD  ',
			'NIBONG TEBAL',
			'P.PINANG',
			'PRAI',
			'RELAU',
			'SG BAKAP',
			'SIMPANG AMPAT',
		],
	},
	{
		state: 'SABAH',
		area: [
			'BEAUFORT',
			'INANAM',
			'KENINGAU',
			'KOTA BELUD',
			'KOTA KINABALU',
			'LAHAD DATU',
			'LIDO',
			'PAPAR',
			'PENAMPANG',
			'SANDAKAN',
			'TAWAU',
		],
	},
	{
		state: 'SARAWAK',
		area: [
			'BATU NIAH',
			'BINTANGOR',
			'BINTULU',
			'KAPIT',
			'KUCHING',
			'LIMBANG',
			'MARUDI',
			'MIRI',
			'MUKAH',
			'SARIKEI',
			'SIBU',
			'SRI AMAN',
		],
	},
	{
		state: 'SELANGOR',
		area: [
			'AMPANG',
			'BANDAR SUNWAY',
			'BANGI',
			'BANTING',
			'BATANG KALI',
			'BDR SG LONG',
			'CHERAS',
			'DAMANSARA',
			'DAMANSARA JAYA',
			'DAMANSARA UTAMA',
			'KAJANG',
			'KAJANG/PUCHONG',
			'KELANA JAYA',
			'KG BARU SUBANG',
			'KLANG',
			'KUALA LANGAT',
			'KUALA SELANGOR',
			'MUTIARA DAMANSARA',
			'PJ',
			'PJ, SS25',
			'PJ, SS3',
			'PUCHONG',
			'RASA',
			'RAWANG',
			'SABAK BERNAM',
			'SEA PARK',
			'SEKINCHAN',
			'SELAYANG',
			'SEMENYIH',
			'SEPANG',
			'SERI KEMBANGAN',
			'SERI SETIA',
			'SG BESAR',
			'SG BULOH',
			'SG CHUA',
			'SG WAY',
			'SHAH ALAM',
			'SS 24/2',
			'SS2/24',
			'SS2/75',
			'SUBANG JAYA',
			'TAIPAN',
			'TAMAN TESTING BERSATU',
			'TG KARANG',
			'USJ',
		],
	},
	{
		state: 'SIEM REAP',
		area: ['KRONG SIEM REAP'],
	},
	{
		state: 'TERENGGANU',
		area: ['CHUKAI', 'DUNGUN', 'K.TERENGGANU', 'KEMAMAN'],
	},
];
