import { StyleSheet } from 'react-native';
import { colors } from 'configs';

export const styles = StyleSheet.create({
	headerContainer: {
		paddingHorizontal: 10,
		borderRadius: 5,
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: colors.primary,
		paddingVertical: 10,
	},
	sectionName: { fontSize: 14, flex: 1, color: colors.white },
	productDetailContainer: {
		backgroundColor: colors.white,
		borderBottomLeftRadius: 5,
		borderBottomRightRadius: 5,
		marginTop: 10,
		marginHorizontal: 5,
	},
	addNewProductContainer: {
		backgroundColor: colors.primary,
		margin: 20,
		marginHorizontal: 30,
		paddingHorizontal: 20,
		paddingVertical: 5,
		flexDirection: 'row',
		borderRadius: 5,
		alignItems: 'center',
		justifyContent: 'center',
	},
	addIcon: { fontSize: 25, color: colors.white },
	addText: { color: colors.white, fontWeight: 'bold', fontSize: 12 },
	borderLine: {
		borderBottomWidth: 2,
		borderRadius: 2,
		borderBottomColor: colors.primary,
		marginBottom: 10,
		marginHorizontal: 10,
	},
	emptyView: { alignItems: 'center', justifyContent: 'center' },
	emptyLottie: { height: 200, width: 200, alignSelf: 'center' },
	dotContainer: {
		flexDirection: 'row',
		justifyContent: 'center',
		padding: 10,
		position: 'absolute',
		alignSelf: 'center',
	},
	dot: {
		borderRadius: 1000,
		marginHorizontal: 5,
		alignSelf: 'center',
	},
	footer: { height: 150 },
	fontSize: { fontSize: 25 },
	questionText: { fontSize: 13, fontWeight: '500', marginTop: 12 },
	answerText: { fontSize: 12, marginTop: 3, textAlign: 'justify' },
	boldText: { fontWeight: 'bold' },
	showMoreButton: {
		justifyContent: 'center',
		marginBottom: 0,
		marginTop: 5,
		backgroundColor: '#0072BC',
		borderRadius: 6,
	},
	icon: { flex: 1.5, right: 100 },
	title: { textAlign: 'center', fontSize: 12 },
});
