const panelClinicList = {
	data: [
		{
			addr: '73, JALAN MAIN DIPLOMATIK, ENGLAVE',
			area: 'PUTRAJAYA',
			clinicCode: null,
			code: 'FT156',
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			hour: 'DAILY/PH 9AM-10PM',
			lat: 2.94496,
			long: 101.723,
			maxGradeCode: null,
			name: 'KLINIK MEDIVIRON',
			noOfDays: 0,
			panelType: null,
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			state: 'KUALA LUMPUR',
			status: null,
			tel: '03-88888004',
			zip: '62050',
		},
		{
			addr: '14 JALAN 6C/7 PERINGKAT 111, BANDAR BARU BANGI',
			area: 'BANGI',
			clinicCode: null,
			code: 'SL8',
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			hour: 'MON-FRI 9AM-9PM, SAT 9AM-5PM, SUN/PH 9AM-1PM',
			lat: 2.94367,
			long: 101.764,
			maxGradeCode: null,
			name: 'POLIKLINIK PENAWAR',
			noOfDays: 0,
			panelType: null,
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			state: 'SELANGOR',
			status: null,
			tel: '03-89256755',
			zip: '43000',
		},
		{
			addr: '5 JALAN 1/8C, SEK 1, BANDAR BARU BANGI',
			area: 'BANGI',
			clinicCode: null,
			code: 'SL7',
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			hour: 'MON-FRI 9AM-1PM, 2PM-5PM, 7PM-9PM, SAT 9AM-1PM',
			lat: 2.94522,
			long: 101.766,
			maxGradeCode: null,
			name: 'KLINIK NG SDN',
			noOfDays: 0,
			panelType: null,
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			state: 'SELANGOR',
			status: null,
			tel: '003-89250185',
			zip: '43650',
		},
		{
			addr: 'NO 3, JALAN M/J 1, TAMAN MAJLIS JAYA',
			area: 'SG CHUA',
			clinicCode: null,
			code: 'SL123',
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			hour: 'MON-SUN/PH 8AM - 10PM',
			lat: 2.9901,
			long: 101.777,
			maxGradeCode: null,
			name: 'KLINIK REDDY KAJANG',
			noOfDays: 0,
			panelType: null,
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			state: 'SELANGOR',
			status: null,
			tel: '03-87339081',
			zip: '43000',
		},
		{
			addr: 'NO. 3 JALAN M/J1,TAMAN MAJLIS JAYA',
			area: 'KAJANG',
			clinicCode: null,
			code: 'SL37',
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			hour: 'MON-SUN/PH 8AM-10PM',
			lat: 2.97477,
			long: 101.786,
			maxGradeCode: null,
			name: 'KLINIK REDDY KAJANG',
			noOfDays: 0,
			panelType: null,
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			state: 'SELANGOR',
			status: null,
			tel: '03-87339081',
			zip: '43000',
		},
		{
			addr: '43, GROUND FLOOR, JALAN MAMANDA 9, AMPANG POINT',
			area: 'AMPANG',
			clinicCode: null,
			code: 'SL6',
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			hour: 'MON-FRI 9AM-9PM, SAT 9AM-2PM',
			lat: 3.15941,
			long: 101.751,
			maxGradeCode: null,
			name: 'KLINIK REDDY AMPANG',
			noOfDays: 0,
			panelType: null,
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			state: 'SELANGOR',
			status: null,
			tel: '003-42576230',
			zip: '68000',
		},
		{
			addr: '78 PERSIARAN RAJA. MUDA MUSA, P.KLANG',
			area: 'KLANG',
			clinicCode: null,
			code: 'SL62',
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			hour: 'DAILY 7AM-10PM',
			lat: 3.00269,
			long: 101.399,
			maxGradeCode: null,
			name: 'PORT DISPENSARY',
			noOfDays: 0,
			panelType: null,
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			state: 'SELANGOR',
			status: null,
			tel: '003-31689944',
			zip: '42000',
		},
		{
			addr: '12A-G, JLN PJS 5/30, PUST DAGANGAN PETALING JAYA SELATAN',
			area: 'PETALING JAYA',
			clinicCode: null,
			code: 'SL180',
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			hour: 'MON-SAT 9AM-9PM',
			lat: 3.07877,
			long: 101.626,
			maxGradeCode: null,
			name: 'POLIKLINIK SHAM',
			noOfDays: 0,
			panelType: null,
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			state: 'SELANGOR',
			status: null,
			tel: '603-77855733',
			zip: '46150',
		},
		{
			addr: '26 JALAN MAXWELL',
			area: 'RAWANG',
			clinicCode: null,
			code: 'SL101',
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			hour: 'MON-FRI 8:30AM-5:30PM, THURS 8:30AM-12:30PM, SUN 8:30AM-5:30PM',
			lat: 3.32118,
			long: 101.576,
			maxGradeCode: null,
			name: 'POLIKLINIK RAWANG',
			noOfDays: 0,
			panelType: null,
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			state: 'SELANGOR',
			status: null,
			tel: '03-60916511',
			zip: '48000',
		},
		{
			addr: '2371 JALAN 1A/3, BANDAR BARU SUNGAI BULOH',
			area: 'SUNGAI BULOH',
			clinicCode: null,
			code: 'SL182',
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			hour: 'DAILY 8:30AM-10:30PM',
			lat: 3.21131,
			long: 101.565,
			maxGradeCode: null,
			name: 'POLIKLINIK PRIMA',
			noOfDays: 0,
			panelType: null,
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			state: 'SELANGOR',
			status: null,
			tel: '003-61575746',
			zip: '47000',
		},
	],
};

const stateList = {
	data: [
		{
			state: 'ALL STATES',
			area: ['ALL STATES'],
		},
		{
			state: 'BATTAMBANG',
			area: ['SANGKAT SVAY POR'],
		},
		{
			state: 'BAVET',
			area: ['SVAY REANG PROVINCE'],
		},
		{
			state: 'JOHOR',
			area: [
				'BATU PAHAT',
				'BUKIT PASIR',
				'CHAAH',
				'ENDAU',
				'J.BAHRU',
				'JOHOR BAHRU',
				'KLUANG',
				'KOTA TINGGI',
				'KULAI',
				'MASAI',
				'MERSING',
				'MUAR',
				'PAGOH',
				'PALOH',
				'PASIR GUDANG',
				'PEKAN NENAS',
				'PLENTONG',
				'PONTIAN KECIL',
				'SEGAMAT',
				'SENAI',
				'SIMPANG RENGAM',
				'SKUDAI',
				'SRI TEBRAU',
				'TAMPOI',
				'TANGKAK',
				'TMN CENTURY',
				'TMN DESA CEMERLANG',
				'TMN JOHOR JAYA',
				'TMN PERLING',
				'TMN SENTOSA',
				'TMN SERI BAHAGIA',
				'TMN SRI BAHAGIA',
				'ULU TIRAM',
				'YONG PENG',
			],
		},
		{
			state: 'KAMPONG CHAM',
			area: ['KRONG KAMPONG CHAM'],
		},
		{
			state: 'KAMPOT',
			area: ['KAMPOT PROVINCE'],
		},
		{
			state: 'KEDAH',
			area: [
				'ALOR SETAR',
				'BALING',
				'CHANGLUN',
				'GUAR CEMPEDAK',
				'GURUN',
				'JITRA',
				'K.KETIL',
				'KULIM',
				'LUNAS',
				'P.LANGKAWI',
				'POKOK SENA',
				'SG PETANI',
				'SIK',
			],
		},
		{
			state: 'KELANTAN',
			area: [
				'GUA MUSANG',
				'K.KRAI',
				'KOTA BAHRU',
				'KUALA KRAI',
				'MACHANG',
				'PASIR MAS',
				'PASIR PUTEH',
				'TANAH MERAH',
			],
		},
		{
			state: 'KUALA LUMPUR',
			area: [
				'AMPANG',
				'BANDAR SRI DAMANSARA',
				'BANGSAR',
				'BATU CAVES',
				'BRICKFIELDS',
				'BUKIT DAMANSARA',
				'CAPITAL SQUARE',
				'CHERAS',
				'DAMANSARA',
				'DAMANSARA HEIGHTS',
				'DESA PANDAN',
				'GOMBAK',
				'JINJANG',
				'JLN ALOR',
				'JLN BUKIT BINTANG',
				'JLN BUKIT NENAS',
				'JLN CHEMUR  ',
				'JLN HANG LEKIU',
				'JLN HJ HUSSIEN',
				'JLN IPOH',
				'JLN KELANG LAMA',
				'JLN KENANGA',
				'JLN KUCHAI LAMA',
				'JLN LOKE YEW',
				'JLN MASJID INDIA',
				'JLN P RAMLEE',
				'JLN PAHANG',
				'JLN PUTRA',
				'JLN RAJA CHULAN',
				'JLN RAJA LAUT',
				'JLN RAJA MUDA ABD AZIZ',
				'JLN SEMANTAN',
				'JLN SG BESI',
				'JLN SULTAN ISMAIL',
				'JLN SULTAN SULAIMAN',
				'JLN TUN RAZAK',
				'JLN TUN TAN SIEW',
				'JLN TUNKU ABD RAHMAN',
				'KAMPUNG BARU',
				'KEPONG',
				'KL CENTRAL',
				'MEDAN PASAR',
				'OUG',
				'PANDAN INDAH',
				'PANDAN JAYA',
				'PANDAN PERDANA',
				'PUDU',
				'PUTRAJAYA',
				'SALAK SOUTH',
				'SEGAMBUT',
				'SENTUL',
				'SERI PETALING',
				'SETAPAK',
				'SRI HARTAMAS',
				'TAMAN DESA',
				'TAMAN MUDA',
				'TMN ANGSANA HILIR',
				'TMN DESA',
				'TMN DESA PETALING',
				'TMN DESA SETAPAK',
				'TMN KERAMAT',
				'TMN MELAWATI',
				'TMN SETIAWANGSA',
				'ULU KELANG',
				'WANGSA MAJU',
			],
		},

		{
			state: 'MELAKA',
			area: [
				'AIR KEROH',
				'AMPANG',
				'BACHANG',
				'BKT BARU',
				'BUKIT BERENDAM',
				'JASIN',
				'JLN BENDAHARA',
				'JLN MELAKA',
				'MASJID TANAH',
				'MELAKA',
				'TMN MALIM JAYA',
				'TREE',
			],
		},
		{
			state: 'NEGERI SEMBILAN',
			area: [
				'BAHAU',
				'BATANG MELAKA',
				'GEMAS',
				'GEMENCHEH',
				'JELEBU',
				'K.KELAWANG',
				'KUALA PILAH',
				'NILAI',
				'PORT DICKSON',
				'RANTAU',
				'RASAH',
				'SEREMBAN',
				'TAMAN SENTOSA DAMAI',
				'TAMPIN',
			],
		},
		{
			state: 'PAHANG',
			area: [
				'BENTONG',
				'BRINCHANG',
				'GENTING HIGHLANDS',
				'JERANTUT',
				'KARAK',
				'KEMAYAN',
				'KUALA .LIPIS',
				'KUALA KRAU',
				'KUALA LIPIS',
				'KUANTAN',
				'MENTAKAB',
				'PEKAN',
				'RAUB',
				'TANAH RATA',
				'TEMERLOH',
				'TRIANG',
			],
		},
		{
			state: 'PERAK',
			area: [
				'AIR TAWAR',
				'BAGAN SERAI',
				'BATU GAJAH',
				'BIDOR',
				'CHEMOR',
				'GUNUNG RAPAT',
				'IPOH',
				'IPOH GARDEN',
				'JLN BERCHAM',
				'JLN PASIR PUTIH',
				'JLN YANG KALSOM',
				'KAMPAR',
				'KAMUNTING',
				'KUALA KANGSAR',
				'LUMUT',
				'MENGLEMBU',
				'PANGKOR',
				'PANTAI REMIS',
				'PARIT BUNTAR',
				'PENGKALAN BARAT',
				'PUSING',
				'SERI MANJUNG',
				'SG SIPUT',
				'SIMPANG AMPAT',
				'SIMPANG PULAI',
				'SITIAWAN',
				'SLIM RIVER',
				'TAIPING',
				'TANJUNG MALIM',
				'TANJUNG PIANDANG',
				'TELUK INTAN',
			],
		},
		{
			state: 'PERLIS',
			area: ['K.PERLIS', 'KANGAR'],
		},
		{
			state: 'PHNOM PENH',
			area: ['PHNOM PENH'],
		},
		{
			state: 'POI PET',
			area: ['POI PET CITY, BANTEYMEANCHEY PROVINCE'],
		},
		{
			state: 'PULAU PINANG',
			area: [
				'AIR ITAM',
				'BAGAN AJAM',
				'BALIK PULAU',
				'BANDAR BARU AIR ITAM',
				'BAYAN BARU',
				'BUKIT MERTAJAM',
				'BUTTERWORTH',
				'GELUGOR',
				'JELUTONG',
				'JLN DATUK KERAMAT',
				'JLN PANGKOR',
				'JLN TAN SRI TEH EWE LIM',
				'KEPALA BATAS',
				'LOGAN ROAD  ',
				'NIBONG TEBAL',
				'P.PINANG',
				'PRAI',
				'RELAU',
				'SG BAKAP',
				'SIMPANG AMPAT',
			],
		},
		{
			state: 'SABAH',
			area: [
				'BEAUFORT',
				'INANAM',
				'KENINGAU',
				'KOTA BELUD',
				'KOTA KINABALU',
				'LAHAD DATU',
				'LIDO',
				'PAPAR',
				'PENAMPANG',
				'SANDAKAN',
				'TAWAU',
			],
		},
		{
			state: 'SARAWAK',
			area: [
				'BATU NIAH',
				'BINTANGOR',
				'BINTULU',
				'KAPIT',
				'KUCHING',
				'LIMBANG',
				'MARUDI',
				'MIRI',
				'MUKAH',
				'SARIKEI',
				'SIBU',
				'SRI AMAN',
			],
		},
		{
			state: 'SELANGOR',
			area: [
				'AMPANG',
				'BANDAR SUNWAY',
				'BANGI',
				'BANTING',
				'BATANG KALI',
				'BDR SG LONG',
				'CHERAS',
				'DAMANSARA',
				'DAMANSARA JAYA',
				'DAMANSARA UTAMA',
				'KAJANG',
				'KAJANG/PUCHONG',
				'KELANA JAYA',
				'KG BARU SUBANG',
				'KLANG',
				'KUALA LANGAT',
				'KUALA SELANGOR',
				'MUTIARA DAMANSARA',
				'PJ',
				'PJ, SS25',
				'PJ, SS3',
				'PUCHONG',
				'RASA',
				'RAWANG',
				'SABAK BERNAM',
				'SEA PARK',
				'SEKINCHAN',
				'SELAYANG',
				'SEMENYIH',
				'SEPANG',
				'SERI KEMBANGAN',
				'SERI SETIA',
				'SG BESAR',
				'SG BULOH',
				'SG CHUA',
				'SG WAY',
				'SHAH ALAM',
				'SS 24/2',
				'SS2/24',
				'SS2/75',
				'SUBANG JAYA',
				'TAIPAN',
				'TAMAN TESTING BERSATU',
				'TG KARANG',
				'USJ',
			],
		},
		{
			state: 'SIEM REAP',
			area: ['KRONG SIEM REAP'],
		},
		{
			state: 'TERENGGANU',
			area: ['CHUKAI', 'DUNGUN', 'K.TERENGGANU', 'KEMAMAN'],
		},
	],
};

export const ClinicData = Object.assign(
	{},
	{
		PanelList: panelClinicList,
		StateList: stateList,
	},
);
