const fetchLeaveBalance = {
	data: [
		{
			accumulated: 0,
			approved: 2,
			balance: 3,
			code: null,
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			entitled: 30,
			leaveCode: 'A001',
			leaveType: 'ANNUAL',
			maxGradeCode: null,
			noOfDays: 0,
			pending: 25,
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			status: null,
			year: '2022',
		},
		{
			accumulated: 0,
			approved: 0,
			balance: 30,
			code: null,
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			entitled: 30,
			leaveCode: 'M002',
			leaveType: 'NON HOSPITALISATION',
			maxGradeCode: null,
			noOfDays: 0,
			pending: 0,
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			status: null,
			year: '2022',
		},
	],
	ok: true,
};

const fetchLeaveRecord = {
	data: [
		{
			code: null,
			company: 'PBB',
			companyCode: null,
			date: '12/14/2022 12:00:00 AM',
			dayType: 0,
			days: 1,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			gradeCode: null,
			leaveCode: 'PPH1',
			levCategory: null,
			maxGradeCode: null,
			noOfDays: 0,
			personId: '39940',
			requesterStaffNo: null,
			stYmth: null,
			staffName: null,
			staffNo: null,
			startDate: null,
			status: null,
		},
		{
			code: null,
			company: 'PBB',
			companyCode: null,
			date: '12/15/2022 12:00:00 AM',
			dayType: 0,
			days: 1,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			gradeCode: null,
			leaveCode: 'PPH1',
			levCategory: null,
			maxGradeCode: null,
			noOfDays: 0,
			personId: '39940',
			requesterStaffNo: null,
			stYmth: null,
			staffName: null,
			staffNo: null,
			startDate: null,
			status: null,
		},
	],
	ok: true,
};

const fetchWorkFromHomeSchedule = {
	data: {
		datesList: ['2/28/2022', '3/1/2022', '3/2/2022', '3/3/2022', '3/4/2022'],
		staffNo: '39940',
	},
	ok: true,
};

const fetchPendingLeave = {
	data: [
		{
			appLeaveDate: [
				{
					dayType: 0,
					leaveDate: '12/30/2022 12:00:00 AM',
				},
			],
			isOnBeHalf: 'N',
			leaveCode: 'A001',
			leaveId: 'A0012884420221130001',
			leaveName: 'ANNUAL',
			name: 'NASRUDIN BIN SALLEH',
			noOfDays: '1',
			personId: '28844',
			reliefName: 'UAT-10006',
			remarks: '',
			submitDate: '11/30/2022 12:00:00 AM',
		},
	],
};

const submitApplyLeave = {
	data: { status: 'Transaction successful' },
	ok: true,
};

const fetchOffDates = {
	data: [
		{
			code: null,
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			maxGradeCode: null,
			noOfDays: 0,
			offDate: '12/17/2022 00:00:00',
			personId: null,
			requesterStaffNo: null,
			stYmth: null,
			staffNo: null,
			startDate: null,
			status: null,
		},
	],
	ok: true,
};

const submitApproveLeave = {
	data: { status: 'Transaction successful' },
	ok: true,
};

const fetchStaffList = {
	data: [
		{
			code: null,
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			maxGradeCode: null,
			name: "AMIRUL 'AIZAT BIN AB RAHIM",
			noOfDays: 0,
			personId: null,
			requesterStaffNo: null,
			selected: null,
			stYmth: null,
			staffNo: '61559',
			startDate: null,
			status: null,
		},
		{
			code: null,
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			maxGradeCode: null,
			name: 'Lee Wee Peng',
			noOfDays: 0,
			personId: null,
			requesterStaffNo: null,
			selected: null,
			stYmth: null,
			staffNo: '60630',
			startDate: null,
			status: null,
		},
	],
	ok: true,
};

const fetchReliefList = {
	data: [
		{
			code: null,
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			maxGradeCode: null,
			name: "AMIRUL 'AIZAT BIN AB RAHIM",
			noOfDays: 0,
			personId: '61559',
			requesterStaffNo: null,
			selected: 'N',
			stYmth: null,
			staffNo: null,
			startDate: null,
			status: null,
		},
		{
			code: null,
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			maxGradeCode: null,
			name: 'Chong Chow Sin',
			noOfDays: 0,
			personId: '64374',
			requesterStaffNo: null,
			selected: 'N',
			stYmth: null,
			staffNo: null,
			startDate: null,
			status: null,
		},
	],
	ok: true,
};

const fetchApproverList = {
	data: [
		{
			code: null,
			companyCode: null,
			divisionCode: null,
			divisionGrpCode: null,
			edYmth: null,
			maxGradeCode: null,
			name: 'NASRUDIN BIN SALLEH',
			noOfDays: 0,
			personId: '28844',
			requesterStaffNo: null,
			selected: 'N',
			stYmth: null,
			staffNo: null,
			startDate: null,
			status: null,
		},
	],
	ok: true,
};

export const LeaveData = Object.assign(
	{},
	{
		LeaveBalance: fetchLeaveBalance,
		LeaveRecord: fetchLeaveRecord,
		WorkFromHome: fetchWorkFromHomeSchedule,
		PendingLeave: fetchPendingLeave,
		SubmitApplyLeave: submitApplyLeave,
		OffDates: fetchOffDates,
		ApproveLeave: submitApproveLeave,
		ApproverList: fetchApproverList,
		ReliefList: fetchReliefList,
		StaffList: fetchStaffList,
	},
);
