import Moment from 'moment/moment';

const today = Moment().toDate();
const formattedToday = Moment(today).format('YYYY-MM-DD');

const fetchReliefAssignment = {
	data: {
		leaveInfo: [
			{
				code: null,
				company: 'PBB',
				companyCode: null,
				date: '3/12/2023 12:00:00 AM',
				dayType: 0,
				days: 1,
				divisionCode: null,
				divisionGrpCode: null,
				edYmth: null,
				gradeCode: null,
				leaveCode: 'PPH1',
				levCategory: null,
				maxGradeCode: null,
				noOfDays: 0,
				personId: '11045',
				requesterStaffNo: null,
				stYmth: null,
				staffName: null,
				staffNo: null,
				startDate: null,
				status: null,
			},
			{
				code: null,
				company: 'PBB',
				companyCode: null,
				date: '3/13/2023 12:00:00 AM',
				dayType: 0,
				days: 1,
				divisionCode: null,
				divisionGrpCode: null,
				edYmth: null,
				gradeCode: '600000',
				leaveCode: 'E001',
				levCategory: 'O',
				maxGradeCode: null,
				noOfDays: 0,
				personId: '11045',
				requesterStaffNo: null,
				stYmth: null,
				staffName: 'UAT-39940',
				staffNo: null,
				startDate: null,
				status: 'Approved',
			},
			{
				code: null,
				company: 'PBB',
				companyCode: null,
				date: '3/14/2023 12:00:00 AM',
				dayType: 1,
				days: 1,
				divisionCode: null,
				divisionGrpCode: null,
				edYmth: null,
				gradeCode: '600000',
				leaveCode: 'E001',
				levCategory: 'O',
				maxGradeCode: null,
				noOfDays: 0,
				personId: '11045',
				requesterStaffNo: null,
				stYmth: null,
				staffName: 'UAT-39940',
				staffNo: null,
				startDate: null,
				status: 'Approved',
			},
			{
				code: null,
				company: 'PBB',
				companyCode: null,
				date: '3/14/2023 12:00:00 AM',
				dayType: 2,
				days: 1,
				divisionCode: null,
				divisionGrpCode: null,
				edYmth: null,
				gradeCode: '600000',
				leaveCode: 'E001',
				levCategory: 'O',
				maxGradeCode: null,
				noOfDays: 0,
				personId: '11045',
				requesterStaffNo: null,
				stYmth: null,
				staffName: 'UAT-39940',
				staffNo: null,
				startDate: null,
				status: 'Approved',
			},
			{
				code: null,
				company: 'PBB',
				companyCode: null,
				date: '3/16/2023 12:00:00 AM',
				dayType: 1,
				days: 1,
				divisionCode: null,
				divisionGrpCode: null,
				edYmth: null,
				gradeCode: '600000',
				leaveCode: 'E001',
				levCategory: 'O',
				maxGradeCode: null,
				noOfDays: 0,
				personId: '11045',
				requesterStaffNo: null,
				stYmth: null,
				staffName: 'UAT-39940',
				staffNo: null,
				startDate: null,
				status: 'Approved',
			},
			{
				code: null,
				company: 'PBB',
				companyCode: null,
				date: '3/17/2023 12:00:00 AM',
				dayType: 1,
				days: 2,
				divisionCode: null,
				divisionGrpCode: null,
				edYmth: null,
				gradeCode: '600000',
				leaveCode: 'E001',
				levCategory: 'O',
				maxGradeCode: null,
				noOfDays: 0,
				personId: '11045',
				requesterStaffNo: null,
				stYmth: null,
				staffName: 'UAT-39940',
				staffNo: null,
				startDate: null,
				status: 'Approved',
			},
			{
				code: null,
				company: 'PBB',
				companyCode: null,
				date: '3/18/2023 12:00:00 AM',
				dayType: 2,
				days: 1,
				divisionCode: null,
				divisionGrpCode: null,
				edYmth: null,
				gradeCode: '600000',
				leaveCode: 'E001',
				levCategory: 'O',
				maxGradeCode: null,
				noOfDays: 0,
				personId: '11045',
				requesterStaffNo: null,
				stYmth: null,
				staffName: 'UAT-39940',
				staffNo: null,
				startDate: null,
				status: 'Approved',
			},
			{
				code: null,
				company: 'PBB',
				companyCode: null,
				date: '3/18/2023 12:00:00 AM',
				dayType: 1,
				days: 2,
				divisionCode: null,
				divisionGrpCode: null,
				edYmth: null,
				gradeCode: '600000',
				leaveCode: 'E001',
				levCategory: 'O',
				maxGradeCode: null,
				noOfDays: 0,
				personId: '11045',
				requesterStaffNo: null,
				stYmth: null,
				staffName: 'UAT-39940',
				staffNo: null,
				startDate: null,
				status: 'Approved',
			},
		],
		reliefInfo: {
			[formattedToday]: [
				{
					date: formattedToday,
					duties: 'HP',
					edYmth: '012',
					halfDayType: 0,
					homeStateName: 'PULAU PINANG',
					index: 5,
					reliefBrh: 'HPCC-CAC(BTW)',
					reliefDate: '2023-03-20T00:00:00',
					stYmth: '001',
					staffId: null,
					year: 0,
				},
			],
		},
	},
	ok: true,
	status: 200,
};

export const ReliefData = Object.assign(
	{},
	{
		ReliefAssigment: fetchReliefAssignment,
	},
);
