export const PIRATE_STATUS = {
	PLAYING: 'PLAYING',
	COMPLETED: 'COMPLETED',
	WIN: 'WIN',
	WRONG: 'WRONG',
	LOST: 'LOST',
};

export const PIRATE_STEPS = {
	REMAINING_6: 6,
	REMAINING_5: 5,
	REMAINING_4: 4,
	REMAINING_3: 3,
	REMAINING_2: 2,
	REMAINING_1: 1,
	GAME_OVER: 0,
	COMPLETED: PIRATE_STATUS.COMPLETED,
	LOST: PIRATE_STATUS.LOST,
};
