const TNC = `
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Public Bank Berhad T&C</title>
    <meta name="PBeXperience" content="Public Bank Berhad" />
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <link href="css/custom.css" rel="stylesheet" type="text/css" />


    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="PBeXperience" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:title" content="PBeXperience Terms and Conditions" />
    <meta property="og:description" content="Manage your Github projects from the palm of your hand." />

    <style>
      .section-title {
      color: #114557;
      margin-top: 20px;
      margin-bottom: 10px;
      font-weight: 400;
      font-size: 20px;
    }
    .section-header{
      font-size: 20px; font-weight: bold; text-align: center; color:black
    }
    </style>
  </head>
  

  <body id="terms-and-conditions">
    
    <div class="container-fluid">
      <div class="row terms-and-conditions-section">
<!--        <div class="col-xs-12 text-center">-->
<!--          <h1 class="title">Terms and Conditions</h1>-->
<!--        </div>-->

        <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
          <div class="content">
            <h1 class="section-header">Public Bank Multi-Factor Authentication (MFA) Terms of Use</h1>
            <h3 class="section-title">01. Introduction</h3>
            <p>
              These Terms of Use ("Terms") govern your access and use of the Public Bank Multi-Factor Authentication System ("System") provided by Public Bank Berhad ("Public Bank”, “the Bank", "We", "Us").  By activating and using the System, you ("You", "Your", “Staff”) agree to be bound by these Terms.
              <p>
            <h3 class="section-title">02. Multi-Factor Authentication System</h3>
            <p>
              The System adds an additional layer of security to your login process for the Bank’s work terminals and devices.  In addition to your existing Active Directory (AD) username and password, you will be required to provide a one-time password (OTP) generated by the System.  The OTP can be obtained through two methods:</p>
			<ol>
  				<li><b>Soft Token:</b> A mobile application called PBeXperience ("PBX") installed on your personal mobile device.</li>
  				<li><b>Hard Token:</b> A physical device provided by the Bank.</li>
			</ol>
			<p>
        You are only allowed to have either one (1) soft token OR hard token active at any one time. Staff are NOT allowed to have more than one (1) token at any one time, regardless of it being a soft or hard token.
			</p>
			<p>
        Should you require to switch from either soft token to hard token or vice versa, you are required to first deactivate your existing token by going through the Integrated User ID Application (“IUIA”) for approval to switch tokens.
			</p>
			<h3 class="section-title">03. Activation and Use</h3>
            <p>
              Prior to using the multi-factor authentication (MFA) service, you are required to:
            </p>
            <ol>
            	<li>Read and agree to these Terms.</li>
            	<li>Activate your token:</li>
            	<ol type="a">
            			<li><b>Soft Token:</b> Follow the in-app activation process within PBeXperience (PBX).</li>
            			<li><b>Hard Token:</b> Follow the activation process through the Identity Access Management (IAM) portal.</li>
				</ol>
            </ol>
			<h3 class="section-title">04. Your Responsibilities</h3>
            <p>
				You are responsible for:
            </p>
            <ol>
            	<li>Keeping your AD username, password, and OTP confidential.
              </li>
            	<li>Not sharing your AD username, password, OTP, or token with anyone, including colleagues, family, or friends. </li>
				<li>Immediately reporting any loss, theft, or suspected compromise of your AD credentials, OTP, or token to Public Bank IT Security.
        </li>
				<li>Using the System in accordance with these Terms and all applicable laws and regulations. This includes the Bank’s Corporate Information Security Management Policy (“CISM”). The definitions for the confidentiality and security measures in these terms of use also extends to all staff personal login credentials (“PLC”).</li>
				<li>Returning your Hard Token (if applicable) to the Bank upon cessation of employment.</li>
            </ol>
            <h3 class="section-title">05. Public Bank's Responsibilities</h3>
            <p>
				The Bank will:
            </p>
            <ol>
            	<li>Maintain the security of the System to a commercially reasonable standard.
              </li>
            	<li>Investigate any reported loss, theft, or suspected compromise of your AD credentials, OTP, or mobile device.
              </li>
				<li>Provide you with access to learning materials/information on the System's usage and security best practices.
        </li>
            </ol>
            <h3 class="section-title">06. Disclaimer of Warranties</h3>
            <p>
              The System is provided "as is" without warranties, express or implied. Public Bank disclaims all warranties, including, but not limited to, warranties of merchantability, fitness for a particular purpose, and non-infringement. Public Bank does not warrant that the System will be uninterrupted or error-free.
			</p>
			<h3 class="section-title">07. Limitation of Liability</h3>
			<p>
        Public Bank will not be liable for any damages arising from your use of the System, including, but not limited to, direct, indirect, incidental, special, consequential, or punitive damages, even if Public Bank has been advised of the possibility of such damages.
			</p>
			<h3 class="section-title">08. Termination of Access</h3>
			<p>
				Public Bank reserves the right, in its sole discretion, to terminate your access to the System at any time for any reason.
			</p>
			<h3 class="section-title">09. Governing Law and Dispute Resolution</h3>
			<p>
        These Terms will be governed by and construed in accordance with the laws of Malaysia.  Any dispute arising out of or relating to these Terms shall be subject to the exclusive jurisdiction of the courts of Malaysia.
			</p>
			<h3 class="section-title">10. Entire Agreement</h3>
			<p>
        These Terms constitute the entire agreement between you and Public Bank with respect to the subject matter hereof and supersede all prior or contemporaneous communications, representations, or agreements, whether oral or written.
			</p>
			<h3 class="section-title">11. Amendment</h3>
			<p>
        Public Bank reserves the right to amend these Terms at any time by posting the revised Terms on the Public Bank intranet. Your continued use of the System after the posting of the revised Terms constitutes your agreement to be bound by the revised Terms.
			</p>
			<h3 class="section-title">12. Severability</h3>
			<p>
        If any provision of these Terms is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall remain in full force and effect.
			</p>
			<h3 class="section-title">13. Consequences of Breach</h3>
			<p>
        Any violation of these Terms by you, including but not limited to:
			</p>
			<ol>
				<li>Sharing your AD credentials, OTP, or token.
        </li>
				<li>Failing to safeguard your token.
        </li>
				<li>Failing to report loss, theft, or suspected compromise of your AD credentials, OTP, or token.
        </li>
				<li>Misusing the System.</li>
				<li>Failing to return your Hard Token upon cessation of employment.
        </li>
			</ol>
			<p>
        may result in the following action by Public Bank, up to and including:
			</p>
			<ol>
				<li>Disciplinary action (if necessary)
        </li>
				<li>Suspension of access to the System
        </li>
				<li>Legal action, including but not limited to civil or criminal proceedings, as Public Bank deems necessary.
        </li>
			</ol>	
			<p>
				You are also responsible for complying with all applicable laws, regulations, and guidelines related to your use of the System.  Failure to comply with such laws and regulations may also result in disciplinary action by Public Bank, as described in Section 13.
			</p>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>`;

export const MFA_TNC = {
	TNC,
};
