export const PBSS_1_IDENTIFY_USER = 'PBSS_1_IDENTIFY_USER';
export const PBSS_2_VALIDATE_PAC = 'PBSS_2_VALIDATE_PAC';
export const PBSS_3_ACTIVATE = 'PBSS_3_ACTIVATE_PBSS';
export const PBSS_4_COMPLETED = 'PBSS_4_COMPLETED';
